src/ABACDemo.Web/Controllers/StorageController.cs
using ABACDemo.Web.Interfaces;
using ABACDemo.Web.Models.StorageController;
using Microsoft.AspNetCore.Mvc;

namespace ABACDemo.Web.Controllers
{
    public class StorageController : Controller
    {
        private readonly IContentsService _contentsService;
        private readonly ILogger<StorageController> _logger;
        private readonly IConfiguration _configuration;

        public StorageController(IContentsService contentsService, IConfiguration configuration, ILogger<StorageController> logger)
        {
            ArgumentNullException.ThrowIfNull(contentsService);
            ArgumentNullException.ThrowIfNull(configuration);
            ArgumentNullException.ThrowIfNull(logger);

            _contentsService = contentsService;
            _configuration = configuration;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var model = new IndexViewModel();
            model.AccountName = _configuration["StorageAccountName"];
            try
            {
                model.Containers = await _contentsService.GetContainersAsync();
            }
            catch (Exception ex)
            {
                model.Exception = ex;
                model.Message = ex.Message;
            }
            return View(model);
        }

        public async Task<ActionResult> Container(string containerName)
        {
            var model = new ContainerViewModel();
            model.AccountName = _configuration["StorageAccountName"];
            model.ContainerName = containerName;

            try
            {
                model.Blobs = await this._contentsService.GetBlobsAsync(model.ContainerName, model.Date);
            }
            catch (Exception ex)
            {
                model.Exception = ex;
                model.Message = ex.Message;
            }

            return View(model);
        }

        public async Task<ActionResult> Blob(string containerName, string blobName)
        {
            var model = new BlobViewModel();
            model.AccountName = _configuration["StorageAccountName"];
            model.ContainerName = containerName;
            try
            {
                model.Blob = await this._contentsService.GetBlobAsync(containerName, blobName);
            }
            catch (Exception ex)
            {
                model.Blob = new Entities.BlobContent() { Name = blobName };
                model.Exception = ex;
                model.Message = ex.Message;
            }
            return View(model);
        }
    }
}

src/ABACDemo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ABACDemo</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ABACDemo.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ABACDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Index">Containers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - ABACDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>